export const componentlist=[
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
    {
        Name:"Accordion",
        Link:"/accordion"
    },
]